fragment ProgramParts on Program {
  __typename
  title
  slug
  type
  badge
  subtitle
  tagline
  taglineBody
  outcomesIntro
  pathwayTitle
  pathwayDescription
  heroImage
  benefits {
    __typename
    title
    description
    icon
  }
  stats {
    __typename
    label
    value
    icon
    sub
  }
  courses {
    __typename
    title
    description
  }
  outcomes {
    __typename
    title
    description
  }
  faqs {
    __typename
    q
    a
  }
}
