//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  program: Program;
  programConnection: ProgramConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProgramArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProgramConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgramFilter>;
};

export type DocumentFilter = {
  program?: InputMaybe<ProgramFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Program | Folder;

export type ProgramBenefits = {
  __typename?: 'ProgramBenefits';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type ProgramStats = {
  __typename?: 'ProgramStats';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
};

export type ProgramCourses = {
  __typename?: 'ProgramCourses';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ProgramOutcomes = {
  __typename?: 'ProgramOutcomes';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ProgramFaqs = {
  __typename?: 'ProgramFaqs';
  q?: Maybe<Scalars['String']['output']>;
  a?: Maybe<Scalars['String']['output']>;
};

export type Program = Node & Document & {
  __typename?: 'Program';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  type?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  taglineBody?: Maybe<Scalars['String']['output']>;
  outcomesIntro?: Maybe<Scalars['String']['output']>;
  pathwayTitle?: Maybe<Scalars['String']['output']>;
  pathwayDescription?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  benefits?: Maybe<Array<Maybe<ProgramBenefits>>>;
  stats?: Maybe<Array<Maybe<ProgramStats>>>;
  courses?: Maybe<Array<Maybe<ProgramCourses>>>;
  outcomes?: Maybe<Array<Maybe<ProgramOutcomes>>>;
  faqs?: Maybe<Array<Maybe<ProgramFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProgramBenefitsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type ProgramStatsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
};

export type ProgramCoursesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ProgramOutcomesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ProgramFaqsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type ProgramFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  taglineBody?: InputMaybe<StringFilter>;
  outcomesIntro?: InputMaybe<StringFilter>;
  pathwayTitle?: InputMaybe<StringFilter>;
  pathwayDescription?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  benefits?: InputMaybe<ProgramBenefitsFilter>;
  stats?: InputMaybe<ProgramStatsFilter>;
  courses?: InputMaybe<ProgramCoursesFilter>;
  outcomes?: InputMaybe<ProgramOutcomesFilter>;
  faqs?: InputMaybe<ProgramFaqsFilter>;
};

export type ProgramConnectionEdges = {
  __typename?: 'ProgramConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Program>;
};

export type ProgramConnection = Connection & {
  __typename?: 'ProgramConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProgramConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProgram: Program;
  createProgram: Program;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProgramArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgramMutation;
};


export type MutationCreateProgramArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgramMutation;
};

export type DocumentUpdateMutation = {
  program?: InputMaybe<ProgramMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  program?: InputMaybe<ProgramMutation>;
};

export type ProgramBenefitsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type ProgramStatsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
};

export type ProgramCoursesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ProgramOutcomesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ProgramFaqsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type ProgramMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  taglineBody?: InputMaybe<Scalars['String']['input']>;
  outcomesIntro?: InputMaybe<Scalars['String']['input']>;
  pathwayTitle?: InputMaybe<Scalars['String']['input']>;
  pathwayDescription?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  benefits?: InputMaybe<Array<InputMaybe<ProgramBenefitsMutation>>>;
  stats?: InputMaybe<Array<InputMaybe<ProgramStatsMutation>>>;
  courses?: InputMaybe<Array<InputMaybe<ProgramCoursesMutation>>>;
  outcomes?: InputMaybe<Array<InputMaybe<ProgramOutcomesMutation>>>;
  faqs?: InputMaybe<Array<InputMaybe<ProgramFaqsMutation>>>;
};

export type ProgramPartsFragment = { __typename: 'Program', title: string, slug: string, type?: string | null, badge?: string | null, subtitle?: string | null, tagline?: string | null, taglineBody?: string | null, outcomesIntro?: string | null, pathwayTitle?: string | null, pathwayDescription?: string | null, heroImage?: string | null, benefits?: Array<{ __typename: 'ProgramBenefits', title?: string | null, description?: string | null, icon?: string | null } | null> | null, stats?: Array<{ __typename: 'ProgramStats', label?: string | null, value?: string | null, icon?: string | null, sub?: string | null } | null> | null, courses?: Array<{ __typename: 'ProgramCourses', title?: string | null, description?: string | null } | null> | null, outcomes?: Array<{ __typename: 'ProgramOutcomes', title?: string | null, description?: string | null } | null> | null, faqs?: Array<{ __typename: 'ProgramFaqs', q?: string | null, a?: string | null } | null> | null };

export type ProgramQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProgramQuery = { __typename?: 'Query', program: { __typename: 'Program', id: string, title: string, slug: string, type?: string | null, badge?: string | null, subtitle?: string | null, tagline?: string | null, taglineBody?: string | null, outcomesIntro?: string | null, pathwayTitle?: string | null, pathwayDescription?: string | null, heroImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, benefits?: Array<{ __typename: 'ProgramBenefits', title?: string | null, description?: string | null, icon?: string | null } | null> | null, stats?: Array<{ __typename: 'ProgramStats', label?: string | null, value?: string | null, icon?: string | null, sub?: string | null } | null> | null, courses?: Array<{ __typename: 'ProgramCourses', title?: string | null, description?: string | null } | null> | null, outcomes?: Array<{ __typename: 'ProgramOutcomes', title?: string | null, description?: string | null } | null> | null, faqs?: Array<{ __typename: 'ProgramFaqs', q?: string | null, a?: string | null } | null> | null } };

export type ProgramConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgramFilter>;
}>;


export type ProgramConnectionQuery = { __typename?: 'Query', programConnection: { __typename?: 'ProgramConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProgramConnectionEdges', cursor: string, node?: { __typename: 'Program', id: string, title: string, slug: string, type?: string | null, badge?: string | null, subtitle?: string | null, tagline?: string | null, taglineBody?: string | null, outcomesIntro?: string | null, pathwayTitle?: string | null, pathwayDescription?: string | null, heroImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, benefits?: Array<{ __typename: 'ProgramBenefits', title?: string | null, description?: string | null, icon?: string | null } | null> | null, stats?: Array<{ __typename: 'ProgramStats', label?: string | null, value?: string | null, icon?: string | null, sub?: string | null } | null> | null, courses?: Array<{ __typename: 'ProgramCourses', title?: string | null, description?: string | null } | null> | null, outcomes?: Array<{ __typename: 'ProgramOutcomes', title?: string | null, description?: string | null } | null> | null, faqs?: Array<{ __typename: 'ProgramFaqs', q?: string | null, a?: string | null } | null> | null } | null } | null> | null } };

export const ProgramPartsFragmentDoc = gql`
    fragment ProgramParts on Program {
  __typename
  title
  slug
  type
  badge
  subtitle
  tagline
  taglineBody
  outcomesIntro
  pathwayTitle
  pathwayDescription
  heroImage
  benefits {
    __typename
    title
    description
    icon
  }
  stats {
    __typename
    label
    value
    icon
    sub
  }
  courses {
    __typename
    title
    description
  }
  outcomes {
    __typename
    title
    description
  }
  faqs {
    __typename
    q
    a
  }
}
    `;
export const ProgramDocument = gql`
    query program($relativePath: String!) {
  program(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProgramParts
  }
}
    ${ProgramPartsFragmentDoc}`;
export const ProgramConnectionDocument = gql`
    query programConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProgramFilter) {
  programConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProgramParts
      }
    }
  }
}
    ${ProgramPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      program(variables: ProgramQueryVariables, options?: C): Promise<{data: ProgramQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramQueryVariables, query: string}> {
        return requester<{data: ProgramQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramQueryVariables, query: string}, ProgramQueryVariables>(ProgramDocument, variables, options);
      },
    programConnection(variables?: ProgramConnectionQueryVariables, options?: C): Promise<{data: ProgramConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramConnectionQueryVariables, query: string}> {
        return requester<{data: ProgramConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramConnectionQueryVariables, query: string}, ProgramConnectionQueryVariables>(ProgramConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  